[package]
name = "token-staking-impl"
version = "1.0.0"
authors = ["Terra Money <core@terra.money>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[features]
interface = ["dep:cw-orch"]

[dependencies]
common = { path = "../common" }
membership-common-api = { path = "../membership-common-api" }
membership-common = { path = "../membership-common" }
cosmwasm-std = "1"
cosmwasm-schema = "1.1"
cw-storage-plus = "1.0.1"
cw-utils = "1.0.1"
cw20 = "1.0.1"
token-staking-api = { path = "../token-staking-api" }
ibc-helpers = { path = "../ibc-helpers" }
itertools = "0.10.5"
thiserror = "1"
cw-orch = {version = "0.18.1", optional = true }
