[package]
name = "common"
version = "0.1.0"
authors = ["Terra Money <core@terra.money>"]
edition = "2021"

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "1"
cw-storage-plus = "1.0.1"
cw20 = "1.0.1"
cw20-base = { version = "1.0.1", features = ["library"] }
schemars = "0.8"
serde = { version = "1", default-features = false, features = ["derive"] }
serde-json-wasm = "0.5.0"
serde_with = { version = "2", features = ["json", "macros"] }
thiserror = "1"

[dev-dependencies]
serde_json = "1.0"
