[package]
name = "enterprise-governance-api"
version = "1.0.0"
authors = ["Terra Money <core@terra.money>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[features]
interface = ["dep:cw-orch"]

[dependencies]
cosmwasm-schema = "1.1"
cosmwasm-std = "1"
poll-engine-api = { path = "../poll-engine-api" }
cw-orch = {version = "0.18.1", optional = true }