[package]
name = "funds-distributor-api"
version = "1.0.0"
authors = ["Terra Money <core@terra.money>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[features]
interface = ["dep:cw-orch"]

[dependencies]
cosmwasm-std = "1"
cosmwasm-schema = "1.1"
cw20 = "1.0.1"
thiserror = "1"
cw-orch = {version = "0.18.1", optional = true }
